### ISSUE TITLE
pip install fails with: No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by dmccracken** [Runnerly/flakon#1]
(python3_flask) dmccracken-mac:~ dmccracken$ pip install flakon
Collecting flakon
  Downloading flakon-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v1/kxh41dhd4xvb026kk63_5cljc6bp0h/T/pip-build-1f544ml8/flakon/setup.py", line 5, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/v1/kxh41dhd4xvb026kk63_5cljc6bp0h/T/pip-build-1f544ml8/flakon/

**Comment by dmccracken** [comment]
I worked around this by downloading the .zip file, unziping it and running 'pip install .' from the directory containing the unzip'd files.

**Comment by surinkim** [comment]
Hello, @dmccracken ,

I've fix this issue, and send a pull request #2 .
Before merge, you can also pip install from github, like below.
`pip install git+https://github.com/Runnerly/flakon.git`

**Comment by digidoggie18** [comment]
I just tried to install this on windows server and windows 11 and run into this exact issue with the fix being downloading the zip and doing pip install. The workaround does not work at the moment. Is there anything I can add to this to help?
